"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class PhonemizerId(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: typing___Text = ...

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id"]) -> None: ...
type___PhonemizerId = PhonemizerId

class CustomPhonemizerProto(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: typing___Text = ...

    @property
    def maps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Map]: ...

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        maps : typing___Optional[typing___Iterable[type___Map]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"maps",b"maps"]) -> None: ...
type___CustomPhonemizerProto = CustomPhonemizerProto

class Map(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    word: typing___Text = ...
    phoneme_groups: typing___Text = ...

    def __init__(self,
        *,
        word : typing___Optional[typing___Text] = None,
        phoneme_groups : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"phoneme_groups",b"phoneme_groups",u"word",b"word"]) -> None: ...
type___Map = Map

class ListCustomPhonemizerResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def phonemizers(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___CustomPhonemizerProto]: ...

    def __init__(self,
        *,
        phonemizers : typing___Optional[typing___Iterable[type___CustomPhonemizerProto]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"phonemizers",b"phonemizers"]) -> None: ...
type___ListCustomPhonemizerResponse = ListCustomPhonemizerResponse

class ListCustomPhonemizerRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    pipeline_ids: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    def __init__(self,
        *,
        pipeline_ids : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"pipeline_ids",b"pipeline_ids"]) -> None: ...
type___ListCustomPhonemizerRequest = ListCustomPhonemizerRequest

class UpdateCustomPhonemizerRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    UpdateMethodValue = typing___NewType('UpdateMethodValue', builtin___int)
    type___UpdateMethodValue = UpdateMethodValue
    UpdateMethod: _UpdateMethod
    class _UpdateMethod(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[UpdateCustomPhonemizerRequest.UpdateMethodValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        extend_hard = typing___cast(UpdateCustomPhonemizerRequest.UpdateMethodValue, 0)
        extend_soft = typing___cast(UpdateCustomPhonemizerRequest.UpdateMethodValue, 1)
        replace = typing___cast(UpdateCustomPhonemizerRequest.UpdateMethodValue, 2)
    extend_hard = typing___cast(UpdateCustomPhonemizerRequest.UpdateMethodValue, 0)
    extend_soft = typing___cast(UpdateCustomPhonemizerRequest.UpdateMethodValue, 1)
    replace = typing___cast(UpdateCustomPhonemizerRequest.UpdateMethodValue, 2)

    id: typing___Text = ...
    update_method: type___UpdateCustomPhonemizerRequest.UpdateMethodValue = ...

    @property
    def maps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Map]: ...

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        update_method : typing___Optional[type___UpdateCustomPhonemizerRequest.UpdateMethodValue] = None,
        maps : typing___Optional[typing___Iterable[type___Map]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"maps",b"maps",u"update_method",b"update_method"]) -> None: ...
type___UpdateCustomPhonemizerRequest = UpdateCustomPhonemizerRequest

class CreateCustomPhonemizerRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    prefix: typing___Text = ...

    @property
    def maps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Map]: ...

    def __init__(self,
        *,
        prefix : typing___Optional[typing___Text] = None,
        maps : typing___Optional[typing___Iterable[type___Map]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"maps",b"maps",u"prefix",b"prefix"]) -> None: ...
type___CreateCustomPhonemizerRequest = CreateCustomPhonemizerRequest
